export const SagaActions = {
    FETCH_RANDOM_COURSES_ASYNC: "FETCH_RANDOM_COURSES_ASYNC",
    FETCH_SEARCH_COURSES_ASYNC: "FETCH_SEARCH_COURSES_ASYNC",
    FETCH_VIDEO_ASYNC: "FETCH_VIDEO_ASYNC",
    SIGNUP_ASYNC:"SIGNUP_ASYNC",
    LOGIN_ASYNC:"LOGIN_ASYNC"
  };